<a href="https://colab.research.google.com/github/Desmyk/PYDATA/blob/main/Panda3_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
# Import the necessary libraries

import numpy as np

import pandas as pd

In [30]:
# Import the first dataset cars1 and cars2.
# assign variable cars1 and cars2

cars1 = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv')

cars2 = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv')

print(cars1)

      mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0    18.0          8           307        130    3504          12.0     70
1    15.0          8           350        165    3693          11.5     70
2    18.0          8           318        150    3436          11.0     70
3    16.0          8           304        150    3433          12.0     70
4    17.0          8           302        140    3449          10.5     70
..    ...        ...           ...        ...     ...           ...    ...
193  24.0          6           200         81    3012          17.6     76
194  22.5          6           232         90    3085          17.6     76
195  29.0          4            85         52    2035          22.2     76
196  24.5          4            98         60    2164          22.1     76
197  29.0          4            90         70    1937          14.2     76

     origin                        car  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
0         1  chevrolet chevelle malibu         NaN          NaN          NaN
1         1          buick skylark 320         NaN          NaN          NaN
2         1         plymouth satellite         NaN          NaN          NaN
3         1              amc rebel sst         NaN          NaN          NaN
4         1                ford torino         NaN          NaN          NaN
..      ...                        ...         ...          ...          ...
193       1              ford maverick         NaN          NaN          NaN
194       1                 amc hornet         NaN          NaN          NaN
195       1         chevrolet chevette         NaN          NaN          NaN
196       1            chevrolet woody         NaN          NaN          NaN
197       2                  vw rabbit         NaN          NaN          NaN

     Unnamed: 12  Unnamed: 13
0            NaN          NaN
1            NaN          NaN
2            NaN          NaN
3            NaN          NaN
4            NaN          NaN
..           ...          ...
193          NaN          NaN
194          NaN          NaN
195          NaN          NaN
196          NaN          NaN
197          NaN          NaN

[198 rows x 14 columns]

In [31]:
# Oops, it seems our first dataset has some unnamed blank columns, fix cars1

cars1 = cars1.loc[:, "mpg":"car"]
cars1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino

In [17]:
# What is the number of observations in each dataset?

observations_cars1 = cars1.shape[0]
observations_cars2 = cars2.shape[0]


print(f"Number of observations in cars1: {observations_cars1}")
print(f"Number of observations in cars2: {observations_cars2}")

Number of observations in cars1: 198
Number of observations in cars2: 200

In [33]:
# Join cars1 and cars2 into a single DataFrame called cars

cars = pd.concat([cars1, cars2])

print(cars)

      mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0    18.0          8           307        130    3504          12.0     70
1    15.0          8           350        165    3693          11.5     70
2    18.0          8           318        150    3436          11.0     70
3    16.0          8           304        150    3433          12.0     70
4    17.0          8           302        140    3449          10.5     70
..    ...        ...           ...        ...     ...           ...    ...
195  27.0          4           140         86    2790          15.6     82
196  44.0          4            97         52    2130          24.6     82
197  32.0          4           135         84    2295          11.6     82
198  28.0          4           120         79    2625          18.6     82
199  31.0          4           119         82    2720          19.4     82

     origin                        car
0         1  chevrolet chevelle malibu
1         1          buick skylark 320
2         1         plymouth satellite
3         1              amc rebel sst
4         1                ford torino
..      ...                        ...
195       1            ford mustang gl
196       2                  vw pickup
197       1              dodge rampage
198       1                ford ranger
199       1                 chevy s-10

[398 rows x 9 columns]

In [35]:
# Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

owners = np.random.randint(15000, high=73001, size=398, dtype='l')
print(owners)

[66365 16409 25547 65972 55200 49982 70644 64469 62029 61535 15811 20148
 33626 24457 33068 72622 32171 17585 68827 38669 31404 46986 36409 68740
 50931 65315 52601 71245 23458 23658 22550 47006 56697 17360 45289 59040
 68309 42992 54263 35960 54669 72637 44223 23639 62732 18642 51708 58215
 32527 23606 17200 36076 25454 53620 44975 46489 40185 69080 48196 68484
 40291 41301 51925 65749 47535 18790 59279 36571 38654 24890 23430 57721
 38658 53972 61888 28356 40289 50172 52659 71062 27518 51464 48054 16104
 56664 34870 63038 60428 19898 15995 70191 43766 31841 15121 49602 31897
 61886 63141 55828 21366 44981 16119 15313 60262 36750 44060 45550 20089
 44950 59009 22650 65028 47889 53600 60546 43273 26926 54095 48327 32597
 18100 19797 17633 65224 54684 20747 68617 33208 51347 67860 27949 64477
 45418 46766 26273 32745 22156 70035 44278 44092 62844 33024 32517 45751
 30506 16122 59029 45535 67898 15199 46721 67138 42510 32130 71143 41911
 45591 62349 60946 21518 49609 71452 45715 37751 66173 47173 53152 49719
 52902 55332 28257 41831 62712 61150 67381 56055 17096 46562 70672 61197
 50668 34631 70658 47139 64066 21651 54638 21127 52321 50701 48014 38010
 45905 72743 71769 66703 66980 52060 34485 28779 47075 36948 58687 69984
 51306 16817 24824 19579 68368 57801 28953 64186 44310 34040 24892 66423
 20756 20199 33005 50176 37056 62820 37979 49254 37318 30492 61786 32280
 57558 37661 51268 16281 56200 37656 58957 26326 35196 35982 61690 60980
 22468 40147 24750 39809 72642 55732 29042 52626 15792 68547 44290 52970
 60540 57164 31150 16410 38553 65209 51405 29274 50762 59926 53201 40934
 34235 19871 42852 44878 59517 44328 71345 30319 47130 72211 29880 17926
 71526 56386 60165 18299 23694 52887 60894 51539 23567 24461 27582 20272
 58844 38823 24066 65972 27881 57525 43132 15363 61140 27239 31232 33489
 47749 19528 56751 42215 46044 23684 69065 47802 31199 69412 44552 54900
 70611 72227 17736 41502 71851 45658 56126 48577 70479 37700 52249 18420
 51985 21522 46627 54130 71521 18643 19121 58683 30310 44270 70033 16297
 52992 56723 47291 23482 38774 66661 26706 23703 56849 66186 67042 43486
 48551 51874 58602 55656 36614 19683 41628 65020 25996 29867 46092 61209
 67883 37768 42854 17725 21362 40827 64391 31480 43673 67740 53926 72108
 64769 60422 41354 45312 32374 22699 16732 48376 36481 31791 55550 26763
 64667 36880 22618 33695 63169 42211 43437 30787 17721 45617 37194 24878
 53633 17587]

In [36]:
# Add the column owners to cars

cars['owners'] = owners
cars.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,45617
196,44.0,4,97,52,2130,24.6,82,2,vw pickup,37194
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage,24878
198,28.0,4,120,79,2625,18.6,82,1,ford ranger,53633
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10,17587