<a href="https://colab.research.google.com/github/Desmyk/PYDATA/blob/main/Pandaweek1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import the necessary libraries
import pandas as pd

In [2]:
# import dataset and Assign it to a variable called
url = 'https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv'
df = pd.read_csv(url)
df.head()

,Date,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
0,2012-12-05,-7426,-6060,-1367,-74,5317,4210,1107,-2183
1,2012-12-12,-8783,-7520,-1263,123,1818,1598,219,-6842
2,2012-12-19,-5496,-5470,-26,-73,103,3472,-3369,-5466
3,2012-12-26,-4451,-4076,-375,550,2610,3333,-722,-1291
4,2013-01-02,-11156,-9622,-1533,-158,2383,2103,280,-8931

In [ ]:
# What is the frequency of the dataset?

# weekly data

In [3]:
# Set the column Date as the index.

df = df.set_index('Date')
df.head()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2012-12-05,-7426,-6060,-1367,-74,5317,4210,1107,-2183
2012-12-12,-8783,-7520,-1263,123,1818,1598,219,-6842
2012-12-19,-5496,-5470,-26,-73,103,3472,-3369,-5466
2012-12-26,-4451,-4076,-375,550,2610,3333,-722,-1291
2013-01-02,-11156,-9622,-1533,-158,2383,2103,280,-8931

In [4]:
# What is the type of the index?
df.index

Index(['2012-12-05', '2012-12-12', '2012-12-19', '2012-12-26', '2013-01-02',
       '2013-01-09', '2014-04-02', '2014-04-09', '2014-04-16', '2014-04-23',
       '2014-04-30', '2014-05-07', '2014-05-14', '2014-05-21', '2014-05-28',
       '2014-06-04', '2014-06-11', '2014-06-18', '2014-06-25', '2014-07-02',
       '2014-07-09', '2014-07-30', '2014-08-06', '2014-08-13', '2014-08-20',
       '2014-08-27', '2014-09-03', '2014-09-10', '2014-11-05', '2014-11-12',
       '2014-11-19', '2014-11-25', '2015-01-07', '2015-01-14', '2015-01-21',
       '2015-01-28', '2015-02-04', '2015-02-11', '2015-03-04', '2015-03-11',
       '2015-03-18', '2015-03-25', '2015-04-01', '2015-04-08'],
      dtype='object', name='Date')

In [5]:
# Set the index to a DatetimeIndex type

df.index = pd.to_datetime(df.index)
type(df.index)

pandas.core.indexes.datetimes.DatetimeIndex

In [6]:
# Change the frequency to monthly, sum the values and assign it to monthly.

monthly = df.resample('M').sum()
monthly

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2012-12-31,-26156,-23126,-3031,526,9848,12613,-2765,-15782
2013-01-31,3661,-1627,5288,2730,12149,9414,2735,18540
2013-02-28,0,0,0,0,0,0,0,0
2013-03-31,0,0,0,0,0,0,0,0
2013-04-30,0,0,0,0,0,0,0,0
2013-05-31,0,0,0,0,0,0,0,0
2013-06-30,0,0,0,0,0,0,0,0
2013-07-31,0,0,0,0,0,0,0,0
2013-08-31,0,0,0,0,0,0,0,0
2013-09-30,0,0,0,0,0,0,0,0
2013-10-31,0,0,0,0,0,0,0,0
2013-11-30,0,0,0,0,0,0,0,0
2013-12-31,0,0,0,0,0,0,0,0
2014-01-31,0,0,0,0,0,0,0,0
2014-02-28,0,0,0,0,0,0,0,0
2014-03-31,0,0,0,0,0,0,0,0
2014-04-30,10842,1048,9794,4931,8493,7193,1300,24267
2014-05-31,-2203,-8720,6518,3172,13767,10192,3576,14736
2014-06-30,2319,-6546,8865,4588,9715,7551,2163,16621
2014-07-31,-7051,-11128,4078,2666,7506,7026,481,3122
2014-08-31,1943,-5508,7452,1885,1897,-1013,2910,5723
2014-09-30,-2767,-6596,3829,1599,3984,2479,1504,2816
2014-10-31,0,0,0,0,0,0,0,0
2014-11-30,-2753,-7239,4485,729,14528,11566,2962,12502
2014-12-31,0,0,0,0,0,0,0,0
2015-01-31,3471,-1164,4635,1729,7368,2762,4606,12569
2015-02-28,5508,3509,1999,1752,9099,7443,1656,16359
2015-03-31,5691,-8176,13867,2829,9138,7267,1870,17657
2015-04-30,379,-4628,5007,970,423,514,-91,1772

In [7]:
# You will notice that it filled the dataFrame with months that don't have any data with NaN.
# Let's drop these rows.

monthly = monthly.dropna()
monthly

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2012-12-31,-26156,-23126,-3031,526,9848,12613,-2765,-15782
2013-01-31,3661,-1627,5288,2730,12149,9414,2735,18540
2013-02-28,0,0,0,0,0,0,0,0
2013-03-31,0,0,0,0,0,0,0,0
2013-04-30,0,0,0,0,0,0,0,0
2013-05-31,0,0,0,0,0,0,0,0
2013-06-30,0,0,0,0,0,0,0,0
2013-07-31,0,0,0,0,0,0,0,0
2013-08-31,0,0,0,0,0,0,0,0
2013-09-30,0,0,0,0,0,0,0,0
2013-10-31,0,0,0,0,0,0,0,0
2013-11-30,0,0,0,0,0,0,0,0
2013-12-31,0,0,0,0,0,0,0,0
2014-01-31,0,0,0,0,0,0,0,0
2014-02-28,0,0,0,0,0,0,0,0
2014-03-31,0,0,0,0,0,0,0,0
2014-04-30,10842,1048,9794,4931,8493,7193,1300,24267
2014-05-31,-2203,-8720,6518,3172,13767,10192,3576,14736
2014-06-30,2319,-6546,8865,4588,9715,7551,2163,16621
2014-07-31,-7051,-11128,4078,2666,7506,7026,481,3122
2014-08-31,1943,-5508,7452,1885,1897,-1013,2910,5723
2014-09-30,-2767,-6596,3829,1599,3984,2479,1504,2816
2014-10-31,0,0,0,0,0,0,0,0
2014-11-30,-2753,-7239,4485,729,14528,11566,2962,12502
2014-12-31,0,0,0,0,0,0,0,0
2015-01-31,3471,-1164,4635,1729,7368,2762,4606,12569
2015-02-28,5508,3509,1999,1752,9099,7443,1656,16359
2015-03-31,5691,-8176,13867,2829,9138,7267,1870,17657
2015-04-30,379,-4628,5007,970,423,514,-91,1772

In [8]:
# Good, now we have the monthly data. Now change the frequency to year.

year = monthly.resample('AS-JAN').sum()
year

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2012-01-01,-26156,-23126,-3031,526,9848,12613,-2765,-15782
2013-01-01,3661,-1627,5288,2730,12149,9414,2735,18540
2014-01-01,330,-44689,45021,19570,59890,44994,14896,79787
2015-01-01,15049,-10459,25508,7280,26028,17986,8041,48357